POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Novo Node",
  "description": "novo video",
  "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/cfd98c19-d201-49eb-86ca-73b0d41287fd
Content-Type: application/json

{
  "title": "Novo video2",
  "description": "novo video2",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/59e1961b-3205-4938-a263-f5522c2b5249