POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Novo Node",
  "description": "novo video",
  "duration": 180
}

###

GET http://localhost:3333/videos?search=Node

###

PUT http://localhost:3333/videos/6012aebc-ba2f-49b2-a45a-a5193539e433
Content-Type: application/json

{
  "title": "Novo video2",
  "description": "novo video2",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/bc694be8-2463-4d3f-aa66-7d5a00aa872b